#!/usr/bin/env python3
"""
🔧 RAULI System Encoding Fix - Corrección completa de encoding UTF-8
"""

import os
import sys
from pathlib import Path

def fix_all_encoding():
    """Corregir encoding en todos los scripts RAULI"""
    print("🔧 Corrigiendo encoding UTF-8 en todos los scripts...")
    
    # Directorio RAULI_CORE
    rauli_core = Path("C:/RAULI_CORE")
    
    # Scripts a corregir
    scripts_to_fix = [
        "rauli_hybrid_system.py",
        "rauli_whatsapp_professional.py",
        "rauli_cloud_architecture.py",
        "rauli_cloud_deployment.py",
        "dashboard_local_system.py"
    ]
    
    for script_name in scripts_to_fix:
        script_path = rauli_core / script_name
        
        if script_path.exists():
            try:
                # Leer con encoding utf-8
                with open(script_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Reemplazar todos los emojis con texto seguro
                emoji_replacements = {
                    '🏗️': '[ARCH]',
                    '🧠': '[AI]',
                    '🌐': '[CLOUD]',
                    '📊': '[METRICS]',
                    '✅': '[OK]',
                    '❌': '[ERROR]',
                    '🔄': '[RESTART]',
                    '⚡': '[SPEED]',
                    '🎯': '[TARGET]',
                    '📱': '[MOBILE]',
                    '💬': '[CHAT]',
                    '🚀': '[BOOT]',
                    '⚠️': '[WARNING]',
                    '🔧': '[FIX]',
                    '📦': '[PACKAGE]',
                    '🔍': '[SEARCH]',
                    '🛡️': '[SECURITY]',
                    '📈': '[GRAPH]',
                    '🔥': '[FIRE]',
                    '💎': '[DIAMOND]',
                    '🌟': '[STAR]',
                    '🎉': '[PARTY]',
                    '📋': '[LIST]',
                    '🔗': '[LINK]',
                    '🔐': '[LOCK]',
                    '📁': '[FOLDER]',
                    '⏱️': '[TIME]',
                    '🌍': '[WORLD]',
                    '🤖': '[ROBOT]',
                    '👁️': '[EYE]',
                    '🖐️': '[HAND]',
                    '🗣️': '[SPEAK]',
                    '📢': '[SPEAKER]',
                    '💡': '[IDEA]',
                    '🎪': '[CIRCUS]',
                    '🏥': '[HOSPITAL]',
                    '☁️': '[CLOUD2]',
                    '📄': '[PAGE]',
                    '🔄': '[RELOAD]',
                    '📡': '[SIGNAL]',
                    '🏆': '[TROPHY]',
                    '🔒': '[LOCKED]',
                    '🌎': '[EARTH]',
                    '📝': '[WRITE]',
                    '🎵': '[MUSIC]',
                    '🎮': '[GAME]',
                    '🎨': '[ART]',
                    '🔬': '[SCIENCE]',
                    '🏢': '[BUILDING]',
                    '🌈': '[RAINBOW]',
                    '⭐': '[STAR2]',
                    '🎭': '[MASK]',
                    '🎪': '[TENT]',
                    '🎯': '[TARGET2]',
                    '🎲': '[DICE]',
                    '🎸': '[GUITAR]',
                    '🎺': '[TRUMPET]',
                    '🥁': '[DRUM]',
                    '🎻': '[VIOLIN]',
                    '🎹': '[PIANO]',
                    '🎤': '[MIC]',
                    '🎧': '[HEADPHONES]',
                    '📻': '[RADIO]',
                    '📺': '[TV]',
                    '📷': '[CAMERA]',
                    '📹': '[VIDEO]',
                    '📼': '[TAPE]',
                    '💿': '[CD]',
                    '💾': '[DISK]',
                    '💽': '[DISK2]',
                    '🖥️': '[COMPUTER]',
                    '⌨️': '[KEYBOARD]',
                    '🖱️': '[MOUSE]',
                    '🖨️': '[PRINTER]',
                    '📠': '[FAX]',
                    '☎️': '[PHONE]',
                    '📱': '[PHONE2]',
                    '📲': '[PHONE3]',
                    '⌚': '[WATCH]',
                    '⏰': '[CLOCK]',
                    '⏳': '[HOURGLASS]',
                    '📅': '[CALENDAR]',
                    '📆': '[CALENDAR2]',
                    '🗓️': '[CALENDAR3]',
                    '📍': '[PIN]',
                    '🚩': '[FLAG]',
                    '🏁': '[FINISH]',
                    '🎌': '[FLAGS]',
                    '🎏': '[FLAG2]',
                    '🏳️': '[FLAG3]',
                    '🏴': '[FLAG4]',
                    '🏳️‍🌈': '[FLAG5]',
                    '🏴‍☠️': '[FLAG6]',
                    '🇦🇨': '[FLAG7]',
                    '🇦🇩': '[FLAG8]',
                    '🇦🇪': '[FLAG9]',
                    '🇦🇫': '[FLAG10]',
                    '🇦🇬': '[FLAG11]',
                    '🇦🇮': '[FLAG12]',
                    '🇦🇱': '[FLAG13]',
                    '🇦🇲': '[FLAG14]',
                    '🇦🇴': '[FLAG15]',
                    '🇦🇶': '[FLAG16]',
                    '🇦🇷': '[FLAG17]',
                    '🇦🇸': '[FLAG18]',
                    '🇦🇹': '[FLAG19]',
                    '🇦🇺': '[FLAG20]',
                    '🇦🇼': '[FLAG21]',
                    '🇦🇽': '[FLAG22]',
                    '🇦🇿': '[FLAG23]',
                    '🇧🇦': '[FLAG24]',
                    '🇧🇧': '[FLAG25]',
                    '🇧🇩': '[FLAG26]',
                    '🇧🇪': '[FLAG27]',
                    '🇧🇫': '[FLAG28]',
                    '🇧🇬': '[FLAG29]',
                    '🇧🇭': '[FLAG30]',
                    '🇧🇮': '[FLAG31]',
                    '🇧🇯': '[FLAG32]',
                    '🇧🇱': '[FLAG33]',
                    '🇧🇲': '[FLAG34]',
                    '🇧🇳': '[FLAG35]',
                    '🇧🇴': '[FLAG36]',
                    '🇧🇶': '[FLAG37]',
                    '🇧🇷': '[FLAG38]',
                    '🇧🇸': '[FLAG39]',
                    '🇧🇹': '[FLAG40]',
                    '🇧🇻': '[FLAG41]',
                    '🇧🇼': '[FLAG42]',
                    '🇧🇾': '[FLAG43]',
                    '🇧🇿': '[FLAG44]',
                    '🇨🇦': '[FLAG45]',
                    '🇨🇨': '[FLAG46]',
                    '🇨🇩': '[FLAG47]',
                    '🇨🇫': '[FLAG48]',
                    '🇨🇬': '[FLAG49]',
                    '🇨🇭': '[FLAG50]',
                    '🇨🇮': '[FLAG51]',
                    '🇨🇰': '[FLAG52]',
                    '🇨🇱': '[FLAG53]',
                    '🇨🇲': '[FLAG54]',
                    '🇨🇳': '[FLAG55]',
                    '🇨🇴': '[FLAG56]',
                    '🇨🇵': '[FLAG57]',
                    '🇨🇶': '[FLAG58]',
                    '🇨🇷': '[FLAG59]',
                    '🇨🇺': '[FLAG60]',
                    '🇨🇻': '[FLAG61]',
                    '🇨🇼': '[FLAG62]',
                    '🇨🇽': '[FLAG63]',
                    '🇨🇾': '[FLAG64]',
                    '🇨🇿': '[FLAG65]',
                    '🇩🇪': '[FLAG66]',
                    '🇩🇯': '[FLAG67]',
                    '🇩🇰': '[FLAG68]',
                    '🇩🇲': '[FLAG69]',
                    '🇩🇴': '[FLAG70]',
                    '🇩🇿': '[FLAG71]',
                    '🇪🇦': '[FLAG72]',
                    '🇪🇨': '[FLAG73]',
                    '🇪🇪': '[FLAG74]',
                    '🇪🇬': '[FLAG75]',
                    '🇪🇭': '[FLAG76]',
                    '🇪🇷': '[FLAG77]',
                    '🇪🇸': '[FLAG78]',
                    '🇪🇹': '[FLAG79]',
                    '🇪🇺': '[FLAG80]',
                    '🇫🇮': '[FLAG81]',
                    '🇫🇯': '[FLAG82]',
                    '🇫🇰': '[FLAG83]',
                    '🇫🇲': '[FLAG84]',
                    '🇫🇴': '[FLAG85]',
                    '🇫🇷': '[FLAG86]',
                    '🇬🇦': '[FLAG87]',
                    '🇬🇧': '[FLAG88]',
                    '🇬🇩': '[FLAG89]',
                    '🇬🇪': '[FLAG90]',
                    '🇬🇫': '[FLAG91]',
                    '🇬🇬': '[FLAG92]',
                    '🇬🇭': '[FLAG93]',
                    '🇬🇮': '[FLAG94]',
                    '🇬🇱': '[FLAG95]',
                    '🇬🇲': '[FLAG96]',
                    '🇬🇳': '[FLAG97]',
                    '🇬🇵': '[FLAG98]',
                    '🇬🇶': '[FLAG99]',
                    '🇬🇷': '[FLAG100]',
                    '🇬🇸': '[FLAG101]',
                    '🇬🇹': '[FLAG102]',
                    '🇬🇺': '[FLAG103]',
                    '🇬🇼': '[FLAG104]',
                    '🇬🇾': '[FLAG105]',
                    '🇭🇰': '[FLAG106]',
                    '🇭🇲': '[FLAG107]',
                    '🇭🇳': '[FLAG108]',
                    '🇭🇷': '[FLAG109]',
                    '🇭🇹': '[FLAG110]',
                    '🇭🇺': '[FLAG111]',
                    '🇮🇨': '[FLAG112]',
                    '🇮🇩': '[FLAG113]',
                    '🇮🇪': '[FLAG114]',
                    '🇮🇱': '[FLAG115]',
                    '🇮🇲': '[FLAG116]',
                    '🇮🇳': '[FLAG117]',
                    '🇮🇴': '[FLAG118]',
                    '🇮🇶': '[FLAG119]',
                    '🇮🇷': '[FLAG120]',
                    '🇮🇸': '[FLAG121]',
                    '🇮🇹': '[FLAG122]',
                    '🇯🇪': '[FLAG123]',
                    '🇯🇲': '[FLAG124]',
                    '🇯🇴': '[FLAG125]',
                    '🇯🇵': '[FLAG126]',
                    '🇰🇪': '[FLAG127]',
                    '🇰🇬': '[FLAG128]',
                    '🇰🇭': '[FLAG129]',
                    '🇰🇮': '[FLAG130]',
                    '🇰🇲': '[FLAG131]',
                    '🇰🇳': '[FLAG132]',
                    '🇰🇵': '[FLAG133]',
                    '🇰🇷': '[FLAG134]',
                    '🇰🇼': '[FLAG135]',
                    '🇰🇾': '[FLAG136]',
                    '🇰🇿': '[FLAG137]',
                    '🇱🇦': '[FLAG138]',
                    '🇱🇧': '[FLAG139]',
                    '🇱🇨': '[FLAG140]',
                    '🇱🇮': '[FLAG141]',
                    '🇱🇰': '[FLAG142]',
                    '🇱🇷': '[FLAG143]',
                    '🇱🇸': '[FLAG144]',
                    '🇱🇹': '[FLAG145]',
                    '🇱🇺': '[FLAG146]',
                    '🇱🇻': '[FLAG147]',
                    '🇱🇾': '[FLAG148]',
                    '🇲🇦': '[FLAG149]',
                    '🇲🇨': '[FLAG150]',
                    '🇲🇩': '[FLAG151]',
                    '🇲🇪': '[FLAG152]',
                    '🇲🇫': '[FLAG153]',
                    '🇲🇬': '[FLAG154]',
                    '🇲🇭': '[FLAG155]',
                    '🇲🇰': '[FLAG156]',
                    '🇲🇱': '[FLAG157]',
                    '🇲🇲': '[FLAG158]',
                    '🇲🇳': '[FLAG159]',
                    '🇲🇴': '[FLAG160]',
                    '🇲🇵': '[FLAG161]',
                    '🇲🇶': '[FLAG162]',
                    '🇲🇷': '[FLAG163]',
                    '🇲🇸': '[FLAG164]',
                    '🇲🇹': '[FLAG165]',
                    '🇲🇺': '[FLAG166]',
                    '🇲🇻': '[FLAG167]',
                    '🇲🇼': '[FLAG168]',
                    '🇲🇽': '[FLAG169]',
                    '🇲🇾': '[FLAG170]',
                    '🇲🇿': '[FLAG171]',
                    '🇳🇦': '[FLAG172]',
                    '🇳🇨': '[FLAG173]',
                    '🇳🇪': '[FLAG174]',
                    '🇳🇫': '[FLAG175]',
                    '🇳🇬': '[FLAG176]',
                    '🇳🇮': '[FLAG177]',
                    '🇳🇱': '[FLAG178]',
                    '🇳🇴': '[FLAG179]',
                    '🇳🇵': '[FLAG180]',
                    '🇳🇷': '[FLAG181]',
                    '🇳🇺': '[FLAG182]',
                    '🇳🇿': '[FLAG183]',
                    '🇴🇲': '[FLAG184]',
                    '🇵🇦': '[FLAG185]',
                    '🇵🇪': '[FLAG186]',
                    '🇵🇫': '[FLAG187]',
                    '🇵🇬': '[FLAG188]',
                    '🇵🇭': '[FLAG189]',
                    '🇵🇰': '[FLAG190]',
                    '🇵🇱': '[FLAG191]',
                    '🇵🇲': '[FLAG192]',
                    '🇵🇳': '[FLAG193]',
                    '🇵🇷': '[FLAG194]',
                    '🇵🇸': '[FLAG195]',
                    '🇵🇹': '[FLAG196]',
                    '🇵🇼': '[FLAG197]',
                    '🇵🇾': '[FLAG198]',
                    '🇵🇿': '[FLAG199]',
                    '🇶🇦': '[FLAG200]',
                    '🇷🇪': '[FLAG201]',
                    '🇷🇴': '[FLAG202]',
                    '🇷🇸': '[FLAG203]',
                    '🇷🇺': '[FLAG204]',
                    '🇷🇼': '[FLAG205]',
                    '🇸🇦': '[FLAG206]',
                    '🇸🇧': '[FLAG207]',
                    '🇸🇨': '[FLAG208]',
                    '🇸🇩': '[FLAG209]',
                    '🇸🇪': '[FLAG210]',
                    '🇸🇬': '[FLAG211]',
                    '🇸🇭': '[FLAG212]',
                    '🇸🇮': '[FLAG213]',
                    '🇸🇯': '[FLAG214]',
                    '🇸🇰': '[FLAG215]',
                    '🇸🇱': '[FLAG216]',
                    '🇸🇲': '[FLAG217]',
                    '🇸🇳': '[FLAG218]',
                    '🇸🇴': '[FLAG219]',
                    '🇸🇷': '[FLAG220]',
                    '🇸🇸': '[FLAG221]',
                    '🇸🇹': '[FLAG222]',
                    '🇸🇻': '[FLAG223]',
                    '🇸🇽': '[FLAG224]',
                    '🇸🇾': '[FLAG225]',
                    '🇸🇿': '[FLAG226]',
                    '🇹🇨': '[FLAG227]',
                    '🇹🇩': '[FLAG228]',
                    '🇹🇫': '[FLAG229]',
                    '🇹🇬': '[FLAG230]',
                    '🇹🇭': '[FLAG231]',
                    '🇹🇯': '[FLAG232]',
                    '🇹🇰': '[FLAG233]',
                    '🇹🇱': '[FLAG234]',
                    '🇹🇲': '[FLAG235]',
                    '🇹🇳': '[FLAG236]',
                    '🇹🇴': '[FLAG237]',
                    '🇹🇷': '[FLAG238]',
                    '🇹🇹': '[FLAG239]',
                    '🇹🇻': '[FLAG240]',
                    '🇹🇼': '[FLAG241]',
                    '🇹🇿': '[FLAG242]',
                    '🇺🇦': '[FLAG243]',
                    '🇺🇬': '[FLAG244]',
                    '🇺🇲': '[FLAG245]',
                    '🇺🇳': '[FLAG246]',
                    '🇺🇸': '[FLAG247]',
                    '🇺🇾': '[FLAG248]',
                    '🇺🇿': '[FLAG249]',
                    '🇻🇦': '[FLAG250]',
                    '🇻🇨': '[FLAG251]',
                    '🇻🇪': '[FLAG252]',
                    '🇻🇬': '[FLAG253]',
                    '🇻🇮': '[FLAG254]',
                    '🇻🇳': '[FLAG255]',
                    '🇻🇺': '[FLAG256]',
                    '🇻🇫': '[FLAG257]',
                    '🇻🇬': '[FLAG258]',
                    '🇻🇭': '[FLAG259]',
                    '🇻🇮': '[FLAG260]',
                    '🇻🇱': '[FLAG261]',
                    '🇻🇲': '[FLAG262]',
                    '🇻🇳': '[FLAG263]',
                    '🇻🇴': '[FLAG264]',
                    '🇻🇺': '[FLAG265]',
                    '🇻🇦': '[FLAG266]',
                    '🇻🇨': '[FLAG267]',
                    '🇻🇪': '[FLAG268]',
                    '🇻🇬': '[FLAG269]',
                    '🇻🇭': '[FLAG270]',
                    '🇻🇮': '[FLAG271]',
                    '🇻🇱': '[FLAG272]',
                    '🇻🇲': '[FLAG273]',
                    '🇻🇳': '[FLAG274]',
                    '🇻🇴': '[FLAG275]',
                    '🇻🇺': '[FLAG276]',
                    '🇼🇫': '[FLAG277]',
                    '🇼🇸': '[FLAG278]',
                    '🇾🇪': '[FLAG279]',
                    '🇾🇹': '[FLAG280]',
                    '🇿🇦': '[FLAG281]',
                    '🇿🇲': '[FLAG282]',
                    '🇿🇼': '[FLAG283]',
                }
                
                # Aplicar reemplazos
                for emoji, replacement in emoji_replacements.items():
                    content = content.replace(emoji, replacement)
                
                # Guardar con encoding utf-8
                with open(script_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                print(f"✅ Script corregido: {script_name}")
                
            except Exception as e:
                print(f"❌ Error corrigiendo {script_name}: {e}")
        else:
            print(f"⚠️ Script no encontrado: {script_name}")

def main():
    """Función principal"""
    print("🔧 RAULI System Encoding Fix - Corrección completa")
    print("=" * 60)
    
    fix_all_encoding()
    
    print("\n✅ Corrección de encoding completada")
    print("🚀 Ahora intenta arrancar el sistema:")
    print("   python rauli_boot_manager.py boot")

if __name__ == "__main__":
    main()
